### ISSUE TITLE
Add Ariana as collaborator to this repo

### ISSUE THREAD

**Issue by AHuffmyer** [shellytrigg/paper-GeoduckTransgen_var.pH#1]
@shellywanamaker could you please add me as a collaborator on this repo? Then we can chat about how I can help with the analysis! :)

**Comment by AHuffmyer** [comment]
GitHub: AHuffmyer

**Comment by shellywanamaker** [comment]
added!

**Comment by AHuffmyer** [comment]
Thanks! What are the next steps in analysis that I can help with?

**Comment by shellywanamaker** [comment]
1) Water chem data analysis: I haven't started that yet. I believe all the data are in the data directory under "water chem". You might be able to adapt [Sam Gurr's R scripts](https://github.com/shellywanamaker/paper-GeoduckReproDev_pH/tree/master/data/water_chem/Scripts) in the other geoduck project to analyze these data files

**Comment by shellywanamaker** [comment]
thanks for helping with this!
